//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestFacturacionMVC.NETFramework.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Detalle
    {
        public int pkIdDetalle { get; set; }
        [Required]
        public Nullable<int> fkIdProducto { get; set; }
        [Required]
        public Nullable<int> fkIdFactura { get; set; }
        [Required]
        [Range(0, 999)]
        public Nullable<int> cantidad { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
